
package Ventanas;

import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mar
 */
public class Administradores extends javax.swing.JFrame {

    /**
     * Creates new form Administradores
     */
    public Administradores() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        SESION = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txt_usu = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_app = new javax.swing.JTextField();
        txt_dire = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        Jerarquia = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();
        search = new javax.swing.JButton();
        help = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Lao UI", 1, 18)); // NOI18N
        jLabel3.setText("Sistema de Gestion de Préstamo de Libros");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        SESION.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CLOSE.png"))); // NOI18N
        SESION.setBorderPainted(false);
        SESION.setContentAreaFilled(false);
        SESION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SESIONActionPerformed(evt);
            }
        });
        getContentPane().add(SESION, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 50, 40));

        jSeparator1.setBackground(new java.awt.Color(153, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(204, 0, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 810, 10));

        txt_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 110, -1));
        getContentPane().add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 110, -1));

        txt_app.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_appActionPerformed(evt);
            }
        });
        getContentPane().add(txt_app, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 110, -1));

        txt_dire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direActionPerformed(evt);
            }
        });
        getContentPane().add(txt_dire, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 110, -1));

        txt_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 110, -1));

        Jerarquia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        Jerarquia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JerarquiaItemStateChanged(evt);
            }
        });
        Jerarquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JerarquiaActionPerformed(evt);
            }
        });
        getContentPane().add(Jerarquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 50, -1));

        jLabel4.setFont(new java.awt.Font("Gautami", 1, 12)); // NOI18N
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gautami", 1, 12)); // NOI18N
        jLabel5.setText("Apellidos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gautami", 1, 12)); // NOI18N
        jLabel6.setText("Direccion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gautami", 1, 12)); // NOI18N
        jLabel7.setText("E-Mail");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabel1.setFont(new java.awt.Font("Gautami", 1, 12)); // NOI18N
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Gautami", 1, 12)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        add.setText("Agregar");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        update.setText("Actualizar");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        delete.setText("Eliminar");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        txt_pass.setText("jPasswordField1");
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/search.png"))); // NOI18N
        search.setBorderPainted(false);
        search.setContentAreaFilled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 30, -1));

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/help.png"))); // NOI18N
        help.setBorderPainted(false);
        help.setContentAreaFilled(false);
        getContentPane().add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 30, 20));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prestamo.jpg"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SESIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SESIONActionPerformed
        Menu obj=new Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_SESIONActionPerformed

    private void txt_direActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direActionPerformed

    private void txt_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mailActionPerformed

    private void JerarquiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JerarquiaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JerarquiaItemStateChanged

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String U,N,A,E,D,P,J;
        
    U=txt_usu.getText();
    N=txt_nom.getText();
    A=txt_app.getText();
    E=txt_mail.getText();
    D=txt_dire.getText();
    P=txt_pass.getText();
    J=Jerarquia.getSelectedItem().toString();
    
        String cadena="update encargados     set Nombre="+"\""+N+"\""+",";
    	cadena=cadena+"Apellidos="+"\""+A+"\""+",";
        cadena=cadena+"Direccion="+"\""+D+"\""+",";
        cadena=cadena+"MAIL="+"\""+E+"\""+",";
        cadena=cadena+"pass="+"\""+P+"\""+",";
       cadena=cadena+"IDRango="+"\""+J+"\""+" ";
    	cadena=cadena+"where Usuario="+"\""+U+"\""+";";
     
    try{PreparedStatement stmt=null;
    	Class.forName("com.mysql.jdbc.Driver");
    	Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca?user=root&password=12345678");
    		stmt =conexion.prepareStatement(cadena);
    		int retorno=stmt.executeUpdate();
    		if(retorno==1){
    			JOptionPane.showMessageDialog(null," Registro Modificado");
    		}
    		if(retorno==0){
    			JOptionPane.showMessageDialog(null,"fracaso de alta");
    		}
    		//aqui va el codigo de la conexion
    	}catch(ClassNotFoundException e){ JOptionPane.showMessageDialog(null,"problema con el driver"); }
    	catch(SQLException e){  JOptionPane.showMessageDialog(null,"problemas con el Query");}
    	catch(Exception e){ JOptionPane.showMessageDialog(null,"problemas con java input-Output de datos");  }	
    }//GEN-LAST:event_updateActionPerformed

    private void txt_appActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_appActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_appActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
    
        if(new ConexionBD().Administradores(txt_usu.getText(), txt_nom.getText(), txt_app.getText(), txt_mail.getText(), txt_dire.getText(),txt_pass.getText(), Jerarquia.getSelectedItem().toString()))
                {
                    
                    JOptionPane.showMessageDialog(null, "Insertado");
                   nuevo();
                   
                }else
        {JOptionPane.showMessageDialog(null, "Intenta de nuevo");}
        
       
        
    
  
    }//GEN-LAST:event_addActionPerformed

    private void JerarquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JerarquiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JerarquiaActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
      
    }//GEN-LAST:event_deleteActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void txt_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuActionPerformed
     String sql="Select * From encargados where Usuario like'%"+txt_usu.getText() + "%'";
      
     
      ConexionBD cc=new ConexionBD();
      Connection cn=cc.conexion();
      try{
          String n="Nombre";
          String a="Apellidos";
          String d="Direccion";
          String m="MAIL";
          String p="pass";
          String j="IDRango";
        
          Statement st = (Statement) cn.createStatement();
          ResultSet rs = st.executeQuery(sql);
          
       if (rs.next()) {
                    txt_nom.setText(rs.getString("Nombre"));
                    txt_app.setText(rs.getString("Apellidos"));
                    txt_mail.setText(rs.getString("MAIL"));
                    txt_dire.setText(rs.getString("Direccion"));
                    txt_pass.setText(rs.getString("pass"));
                    Jerarquia.setSelectedItem(rs.getString("IDRango"));
                }
       else{
       JOptionPane.showMessageDialog(null, "Registro No encontrado ");
       };}
      catch(SQLException e){  JOptionPane.showMessageDialog(null,"Problemas con el Query");}
    	catch(Exception e){ JOptionPane.showMessageDialog(null,"Problemas con java input-Output de datos");  }
    }//GEN-LAST:event_txt_usuActionPerformed

   public void nuevo (){
 txt_usu.setText("");
     txt_nom.setText("");
    txt_app.setText("");
     txt_mail.setText("");
     txt_dire.setText("");
     txt_pass.setText("");
     Jerarquia.getSelectedItem();
     
 
 }
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JComboBox<String> Jerarquia;
    private javax.swing.JButton SESION;
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton search;
    private javax.swing.JTextField txt_app;
    private javax.swing.JTextField txt_dire;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_usu;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
