
package Ventanas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class Devolucion extends javax.swing.JFrame {

     private JTable table;
DefaultTableModel model;
ListSelectionModel lscodigos;

    public Devolucion() {
      
       
        
        
        initComponents();
        
         this.red.setVisible(false);
        this.Sancion.setVisible(false);
         this.name.setVisible(false);
          this.last.setVisible(false);
        this.ema.setVisible(false);
        this.tel.setVisible(false);
	this.add.setVisible(false);
	this.one.setVisible(false);
       this.two.setVisible(false);
        this.three.setVisible(false);
         this.four.setVisible(false);
         
           this.setLocationRelativeTo(null);
        
         Pedidos.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        
        public void valueChanged(ListSelectionEvent e){
        if(Pedidos.getSelectedRow() !=-1)
                {
                    int fila= Pedidos.getSelectedRow();
                    Ma.setText(Pedidos.getValueAt(fila, 3).toString());
                    txt_pie.setText(Pedidos.getValueAt(fila, 1).toString());
                    mjc.setText(Pedidos.getValueAt(fila, 2).toString());
                    
                    
                   
                
                        
                }
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Matri = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pedidos = new javax.swing.JTable();
        FeIn = new javax.swing.JTextField();
        FeFi = new javax.swing.JTextField();
        Encargado = new javax.swing.JLabel();
        Matricula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mjc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        MENU = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        REPORTE = new javax.swing.JButton();
        red = new javax.swing.JLabel();
        Sancion = new javax.swing.JComboBox<>();
        three = new javax.swing.JLabel();
        one = new javax.swing.JLabel();
        two = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        four = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        last = new javax.swing.JLabel();
        ema = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        txt_pie = new javax.swing.JTextField();
        Ma = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        uno = new javax.swing.JTextField();
        statuss = new javax.swing.JLabel();
        di = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Matri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriActionPerformed(evt);
            }
        });
        Matri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MatriKeyPressed(evt);
            }
        });
        getContentPane().add(Matri, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 200, -1));

        Delete.setText("Devolver");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        Pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Pedidos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 690, 110));

        FeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeInActionPerformed(evt);
            }
        });
        getContentPane().add(FeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 110, -1));
        getContentPane().add(FeFi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 100, -1));

        Encargado.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        Encargado.setText(".");
        getContentPane().add(Encargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 90, -1));

        Matricula.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        Matricula.setText("Teclea Matricula");
        getContentPane().add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel2.setText("Fecha Inicial");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel3.setText("Fecha Devolucion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        mjc.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        mjc.setText("MJC");
        getContentPane().add(mjc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 70, 20));

        jLabel4.setFont(new java.awt.Font("Lao UI", 1, 18)); // NOI18N
        jLabel4.setText("Sistema de Gestion de Préstamo de Libros");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 790, 20));

        MENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/menu_1.png"))); // NOI18N
        MENU.setBorderPainted(false);
        MENU.setContentAreaFilled(false);
        MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENUActionPerformed(evt);
            }
        });
        getContentPane().add(MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 60, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/help.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 60, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CLOSE.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 50, 40));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 790, 10));

        REPORTE.setBackground(new java.awt.Color(204, 0, 0));
        REPORTE.setForeground(new java.awt.Color(255, 255, 255));
        REPORTE.setText("Poner Reporte");
        REPORTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTEActionPerformed(evt);
            }
        });
        getContentPane().add(REPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, -1, -1));

        red.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        red.setForeground(new java.awt.Color(204, 51, 0));
        red.setText("Rojo");
        getContentPane().add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        Sancion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(Sancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        three.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        three.setText("1.-Sino ha entregado en la Fecha de Devolucion");
        getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        one.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        one.setText("2.-Si ha entregado el libro en malas condiciones");
        getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        two.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        two.setText("3.-Si ha tratado de llevar algun libro sin hacer el proceso correspondiente");
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        add.setText("Agregar ");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel9.setText("Encargado");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, -1));

        four.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/czerwona.png"))); // NOI18N
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, -1, -1));

        name.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        name.setText("nombre");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        last.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        last.setText("apellido");
        getContentPane().add(last, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        ema.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        ema.setText("e-mail");
        getContentPane().add(ema, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        tel.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        tel.setText("tel");
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prestamo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 540));
        getContentPane().add(txt_pie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, -1));

        Ma.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        Ma.setText("xxxxxxxxxx");
        Ma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaMouseClicked(evt);
            }
        });
        Ma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MaKeyTyped(evt);
            }
        });
        getContentPane().add(Ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        uno.setText("1");
        getContentPane().add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        statuss.setText("jLabel11");
        getContentPane().add(statuss, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, -1));

        di.setText("jLabel12");
        getContentPane().add(di, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MatriKeyPressed
      String [] Titulos={"::..N Pieza..::","::.IDPedido..::","::.Clave Libro..::","::.Matricula..::"};
       String [] Regial= new String[10];
       
       String sql="Select * From piezas where Matricula like'%"+Matri.getText() + "%'";
       
       model= new DefaultTableModel(null, Titulos);
      ConexionBD cc=new ConexionBD();
      Connection cn=cc.conexion();
      
      try{
          Statement st = (Statement) cn.createStatement();
          ResultSet rs = st.executeQuery(sql);
       while (rs.next()) {
                    Regial[0] = rs.getString("IDPiezas");
                    Regial[1] = rs.getString("IDPedidos");
                    Regial[2] = rs.getString("IDLibro");
                    Regial[3] = rs.getString("Matricula");
                    
                    
                    model.addRow(Regial);
                }
       Pedidos.setModel(model);}
       catch(SQLException e){  JOptionPane.showMessageDialog(null,"Problemas con el Query");}
    	catch(Exception e){ JOptionPane.showMessageDialog(null,"Problemas con java input-Output de datos");  }
      
      
      llamada();
    }//GEN-LAST:event_MatriKeyPressed

    private void MatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriActionPerformed

    private void FeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FeInActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
    
    String idl;
    
    idl=mjc.getText();
        
        String cadena="DELETE FROM piezas WHERE IDLibro="+"\""+idl+"\""+";";
    
    	try{PreparedStatement stmt=null;
    	Class.forName("com.mysql.jdbc.Driver");
    	Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca?user=root&password=12345678");
    		stmt =conexion.prepareStatement(cadena);
    		int retorno=stmt.executeUpdate();
    		if(retorno==1){
    			JOptionPane.showMessageDialog(null,"Gracias!");
                        calcular();
                        
    		}
    		if(retorno==0){
    			
                        
    		}
    		//aqui va el codigo de la conexion
    	}catch(ClassNotFoundException e){ JOptionPane.showMessageDialog(null,"Problema con el driver"); }
    	catch(SQLException e){  JOptionPane.showMessageDialog(null,"Problemas con el Query");}
    	catch(Exception e){ JOptionPane.showMessageDialog(null,"Problemas con java input-Output de datos");  }
    }//GEN-LAST:event_DeleteActionPerformed

    private void MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENUActionPerformed
        Menu obj=new Menu();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_MENUActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  Inicio obj=new Inicio();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void MaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaKeyTyped

    }//GEN-LAST:event_MaKeyTyped

    private void MaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaMouseClicked

    }//GEN-LAST:event_MaMouseClicked

    private void REPORTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTEActionPerformed
     llamada2();
    }//GEN-LAST:event_REPORTEActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
     if(new ConexionBD().Reporte(Matri.getText(), Sancion.getSelectedItem().toString() ))
                {
                    JOptionPane.showMessageDialog(null, "Reporte añadido");
                    modificar();
             
                }else
        {JOptionPane.showMessageDialog(null, "Intenta de nuevo");}
     
     
    }//GEN-LAST:event_addActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      AyudaDev obj= new AyudaDev();
      obj.setVisible(true); 
    }//GEN-LAST:event_jButton6ActionPerformed

    
    public void llamada(){
        String sql="Select * From prestamos where Matricula like'%"+Matri.getText() + "%'";
      
     
      ConexionBD cc=new ConexionBD();
      Connection cn=cc.conexion();
      try{
          
          String t="FechaInicio";
          String c="FechaFinal";
          String s="Status";
          String m="Usuario";
        
          Statement st = (Statement) cn.createStatement();
          ResultSet rs = st.executeQuery(sql);
          
       if (rs.next()) {
                    FeIn.setText(rs.getString("FechaInicio"));
                    FeFi.setText(rs.getString("FechaFinal"));
                    uno.setText(rs.getString("Status"));
                    Encargado.setText(rs.getString("Usuario"));
                  
                }
       else{
       JOptionPane.showMessageDialog(null, "MMMMM ");
       };}
      catch(SQLException e){  JOptionPane.showMessageDialog(null,"Problemas con el Query");}
    	catch(Exception e){ JOptionPane.showMessageDialog(null,"Problemas con java input-Output de datos");  }
    
    
    }
    
    public void llamada2(){
        
          this.red.setVisible(true);
        this.Sancion.setVisible(true);
         this.name.setVisible(true);
          this.last.setVisible(true);
        this.ema.setVisible(true);
        this.tel.setVisible(true);
	this.add.setVisible(true);
	this.one.setVisible(true);
       this.two.setVisible(true);
        this.three.setVisible(true);
         this.four.setVisible(true);
        
        
        
    String sql="Select * From alumnos where Matricula like'%"+Matri.getText() + "%'";
      
     
      ConexionBD cc=new ConexionBD();
      Connection cn=cc.conexion();
      try{
          
          String n="Nombre";
          String a="Apellidos";
          String m="Mail";
          String t="Telefono";
          String s="Status";
          String d="Direccion";
        
          Statement st = (Statement) cn.createStatement();
          ResultSet rs = st.executeQuery(sql);
          
       if (rs.next()) {
                    name.setText(rs.getString("Nombre"));
                    last.setText(rs.getString("Apellidos"));
                    ema.setText(rs.getString("Mail"));
                    tel.setText(rs.getString("Telefono"));
                    statuss.setText(rs.getString("Status"));
                    di.setText(rs.getString("Direccion"));
                    
                  
                }
       else{
       JOptionPane.showMessageDialog(null, "MMMMM ");
       };}
      catch(SQLException e){  JOptionPane.showMessageDialog(null,"Problemas con el Query");}
    	catch(Exception e){ JOptionPane.showMessageDialog(null,"Problemas con java input-Output de datos");  }
    
    }
    
    public void modificar(){
    
    String M,N,A,D,T,EM,S;
        
    M=name.getText();
    N=last.getText();
    A=di.getText();
    D=tel.getText();
    T=ema.getText();
    EM=red.getText();
    S=Matri.getText();
    
    
      String cadena="update alumnos set Nombre="+"\""+M+"\""+",";
    	cadena=cadena+"Apellidos="+"\""+N+"\""+",";
        cadena=cadena+"Direccion="+"\""+A+"\""+",";
        cadena=cadena+"Telefono="+"\""+D+"\""+",";
        cadena=cadena+"Mail="+"\""+T+"\""+",";
        cadena=cadena+"Status="+"\""+EM+"\""+" ";
    	cadena=cadena+"where Matricula="+"\""+S+"\""+";";
     
    try{PreparedStatement stmt=null;
    	Class.forName("com.mysql.jdbc.Driver");
    	Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/biblioteca?user=root&password=12345678");
    		stmt =conexion.prepareStatement(cadena);
    		int retorno=stmt.executeUpdate();
    		if(retorno==1){
    			
    		}
    		if(retorno==0){
    			JOptionPane.showMessageDialog(null,"No modificad");
    		}
    		//aqui va el codigo de la conexion
    	}catch(ClassNotFoundException e){ JOptionPane.showMessageDialog(null,"problema con el driver"); }
    	catch(SQLException e){  JOptionPane.showMessageDialog(null,"problemas con el Query");}
    	catch(Exception e){ JOptionPane.showMessageDialog(null,"problemas con java input-Output de datos");  }	
    
    }
    public void calcular(){};
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Devolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Encargado;
    private javax.swing.JTextField FeFi;
    private javax.swing.JTextField FeIn;
    private javax.swing.JButton MENU;
    private javax.swing.JLabel Ma;
    private javax.swing.JTextField Matri;
    private javax.swing.JLabel Matricula;
    private javax.swing.JTable Pedidos;
    private javax.swing.JButton REPORTE;
    private javax.swing.JComboBox<String> Sancion;
    private javax.swing.JButton add;
    private javax.swing.JLabel di;
    private javax.swing.JLabel ema;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel four;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel last;
    private javax.swing.JLabel mjc;
    private javax.swing.JLabel name;
    private javax.swing.JLabel one;
    private javax.swing.JLabel red;
    private javax.swing.JLabel statuss;
    private javax.swing.JLabel tel;
    private javax.swing.JLabel three;
    private javax.swing.JLabel two;
    private javax.swing.JTextField txt_pie;
    private javax.swing.JTextField uno;
    // End of variables declaration//GEN-END:variables
}
