/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Mar
 */
public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu2() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Inicio ini= new Inicio();
    usua.setText(ini.usu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PRESTAMOS = new javax.swing.JButton();
        ALUMNOS = new javax.swing.JButton();
        INVENTARIO = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SESION = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        usua = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 563));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PRESTAMOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/prestamo1.png"))); // NOI18N
        PRESTAMOS.setBorderPainted(false);
        PRESTAMOS.setContentAreaFilled(false);
        PRESTAMOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PRESTAMOS.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosPresed/158prestamo.png"))); // NOI18N
        PRESTAMOS.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosPresed/158prestamo.png"))); // NOI18N
        PRESTAMOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRESTAMOSActionPerformed(evt);
            }
        });
        getContentPane().add(PRESTAMOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 180, 160));

        ALUMNOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1499044376_Student-3.png"))); // NOI18N
        ALUMNOS.setBorderPainted(false);
        ALUMNOS.setContentAreaFilled(false);
        ALUMNOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ALUMNOS.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosPresed/158alumno.png"))); // NOI18N
        ALUMNOS.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosPresed/158alumno.png"))); // NOI18N
        ALUMNOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALUMNOSActionPerformed(evt);
            }
        });
        getContentPane().add(ALUMNOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 190, 160));

        INVENTARIO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1499044246_bookshelf.png"))); // NOI18N
        INVENTARIO.setBorderPainted(false);
        INVENTARIO.setContentAreaFilled(false);
        INVENTARIO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INVENTARIO.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosPresed/158inventario.png"))); // NOI18N
        INVENTARIO.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosPresed/158inventario.png"))); // NOI18N
        INVENTARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INVENTARIOActionPerformed(evt);
            }
        });
        getContentPane().add(INVENTARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 170, 160));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Lao UI", 1, 18)); // NOI18N
        jLabel3.setText("Sistema de Gestion de Préstamo de Libros");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Inventario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Alumnos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setText("Prestamo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/biblioteca.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 360, 170));

        SESION.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CLOSE.png"))); // NOI18N
        SESION.setBorderPainted(false);
        SESION.setContentAreaFilled(false);
        SESION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SESIONActionPerformed(evt);
            }
        });
        getContentPane().add(SESION, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 50, 40));

        jSeparator1.setBackground(new java.awt.Color(153, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(204, 0, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 870, 10));

        jLabel8.setFont(new java.awt.Font("David", 0, 14)); // NOI18N
        jLabel8.setText("Bienvenido");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        usua.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        usua.setText("nombre");
        getContentPane().add(usua, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 14, 130, 22));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimal.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PRESTAMOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRESTAMOSActionPerformed
        Prestamos_1 obj=new Prestamos_1();
        obj.setVisible(true);
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_PRESTAMOSActionPerformed

    private void ALUMNOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALUMNOSActionPerformed
        Alumnos_1 obj=new Alumnos_1();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ALUMNOSActionPerformed

    private void INVENTARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INVENTARIOActionPerformed
        Inventario_1 obj=new Inventario_1();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_INVENTARIOActionPerformed

    private void SESIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SESIONActionPerformed
        Inicio obj=new Inicio();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_SESIONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALUMNOS;
    private javax.swing.JButton INVENTARIO;
    private javax.swing.JButton PRESTAMOS;
    private javax.swing.JButton SESION;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel usua;
    // End of variables declaration//GEN-END:variables
}
